baseURL = "https://thecyberlearner.github.io"
languageCode = "en-us"
title = "Peter Wambua's blog"
theme = "github-style"


[params]
	author = "Peter Wambua"
	description = "Cyber Security Engineer. Red Teamer. CTF Player @Fr334aks-mini"
	avatar = "/images/profile.png"
	url = "https://wambuapeter.github.io"
	twitter = "th3cyberlearner"
	linkedin = "peter-wambua"
	github = "wambuapeter"


